nodeLinker: node-modules
nmMode: hardlinks-local
enableGlobalCache: true
enableImmutableInstalls: false
enableInlineBuilds: true
compressionLevel: mixed
checksumBehavior: throw
yarnPath: .yarn/releases/yarn-4.11.0.cjs

npmRegistryServer: "https://registry.npmjs.org/"
httpTimeout: 120000
httpRetry: 5
